language: nix
# container based has 4G ram which is not enough for haskell deps to compile
sudo: true
matrix:
  include:
    - env: HLINT=true
    - os: osx
      osx_image: xcode8.3
  # due to too long builds
  # https://github.com/NixOS/nixpkgs/issues/21200
  fast_finish: true
env:
- NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/8bed8fb53227932886ab23e5f5f9eabe139f8e9f.tar.gz
cache:
  directories:
  - "$HOME/.stack"
  #- "$HOME/build/input-output-hk/cardano-sl/.stack-work"

before_install:
- echo $TRAVIS_OS_NAME
- export CSL_SYSTEM_TAG=$TRAVIS_OS_NAME
- mkdir -p ~/.local/bin s3
- export PATH=$HOME/.local/bin:$PATH
- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true
# TODO: https://github.com/NixOS/nixpkgs/issues/21200
- travis_retry curl -L https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64 | tar
  xz --strip-components=1 -C ~/.local/bin
- sudo service --status-all || true
- sudo /etc/init.d/memcached stop || true
- sudo /etc/init.d/mysql stop || true
- sudo /etc/init.d/postgresql stop || true

after_failure:
- sudo dmesg

script:
- if [[ "$HLINT" == "true" ]]; then
    nix-shell -p haskellPackages.hlint moreutils --run "util-scripts/lint.sh --nix | ts";
  else
    nix-shell -p moreutils expect --run "unbuffer ./util-scripts/travis.sh | ts";
  fi

deploy:
  provider: s3
  access_key_id: AKIAJKSJR3FUN3CWKC5Q
  secret_access_key:
    secure: PtDmmCXYtnIvoR2j17TJNqdEtAWyeN1JN7x8Ecs47C/77lUxuHIJn/9iqyWYHRqkc0pJvanUHmYQY1dxQTHmIdcZwPaI7i9Hib5xEpi+1AKleZ4fTxiJ9Vt1V7cmCnx9HJ8KEmzbmrD9fPj5N2sl/ROYGWa+gNN89UsX462ms577jSBhdvJcaIeACbyEmnFDct0l5Hv23SF3Ciljiva+OLtSahuuhWjTmjb8kS/KjhU5Sl2uF5ZPsi9Xt7y9w3hvowQn/YCxz+161ekKDQkdWPaIYD0xawo6U5Z/GX3HGUYmZBZvlwEaCDa88dXrEfaxH9eYrRyRSuf93DIDMCdiWAWDf1vZBxYuTH8B88ptgjh9xGYMFdUtLq7sWtoMumYWsW8ldnImI1Y1zNdBXV0LrSmKV5Gy0E1cHYyv+rNCcR5tXBlkVOLRKnVLxA8XGfQjFCTQwaljarx7NKqToHzkOb9uiOvPyBvD6WQTYEeebzop/Uj6rFxOLjJ1Fb7xM6zeLkFktEThReDFefX34a8qzD6YnJuBbVTOvROoBC06I4FaBo5rwrpHe7tLohwxLASdhrCy/e6SMsehEOS+luwHNDEV95TnzcNDITqzKQHPdI1J0OYXEal3MkhYwYEtGuwnNDOEfd1nm+2BSw8L0F+pAyP/GBlnLUO9QVg+LWvKOfw=
  bucket: cardano-sl-travis
  region: eu-central-1
  local_dir: s3
  acl: public_read
  skip_cleanup: true
  on:
    all_branches: true
notifications:
  email: false
  slack:
    secure: HRcMUU+/MNGP3TS3Ta61y8ouDh865zJm/iS6tnDWjajsJC1cvQmUKzBJGSfAl7fCCznDJowsX3p33TyQq1Ulb+SKD88Umb5QaTDyINepUhrirUVdkHTn3o61wauib6lpyuSi7c1CjfGe2Oh4nD+z7AidRSBhxUeeJvROMVPNDRMWfz8hxgII/qWdxucpJ2LphqbOlq3KefUdq8Z3VGm5Nu1QhkIZvrzEzPgCbNz+L+reVIGLPlPYEEkxY/zOZeerIgbfHVyxgxXAxx81r5dQbnNH628gmDOHRq98Bgsp1lqCKuf0A8iAWpxE9ru9VTV4AdydR4IMeKnxlXSEuusGDJ9l2VXSA9tN8yoxiLFwedNly6kQOUgQLPjzzXAbafKTjMvyCdFrUmQPmebBdv+l27HCuyLvVqKrydnNFQjhLX8Nfxf1uOCoYrAk67dU+9HKHYvVavuHD1BVwNfi1V5StfiIWNZTOdSmE5fpCfNYlSDiDD+pxMmI/smeFbrzsiZCE4wBW7CFrZ3ENZ2C07Lz88ip7nCrrPzc7RUmVQg5fELquadKMQ5R013S0/pIuSbgc4aQmsxMhabQ8JgOUYTKVX+cx3JTVTVHZ67JE/WA/3y2Hjune3D8rCIbdJ5sj63lts7aQLMUyBMSdahYKjSHgHuaULg2k1UAc90sLyDe3HM=
    on_success: change
    on_failure: change
