rotation:
    logLimit: 2097152 # 2MB
    keepFiles: 20
severity: Info
node:
    severity: Debug
    handlers:
      - file: node.pub
        round: 5
      - file: node
    comm:
        severity: Info
    dht:
        severity: Info
