# This template is used in scripts to connect to a running cluster.

rotation:
    logLimit: 2097152 # 2MB
    keepFiles: 20
severity: Debug
termSeverity: Debug
handlers:
  - file: node.pub
    round: 5
  - file: node
