##############################################################################
##                                                                          ##
##   Development config                                                     ##
##                                                                          ##
##############################################################################

dev: &dev

  core: &dev_core

    genesis: &dev_core_genesis
      # To use a canonical JSON genesis, use the 'src' key instead of 'spec'.
      # src: './genesis.json'
      spec: &dev_core_genesis_spec
        initializer:
          testnetInitializer:
            testBalance:
              poors:        12
              richmen:      4
              richmenShare: 0.99
              useHDAddresses: False
              totalBalance: 600000000000000000
            fakeAvvmBalance: 
              count: 10
              oneBalance: 100000
            distribution: 
              testnetRichmenStakeDistr: []
            seed: 0
        blockVersionData: &dev_core_genesis_spec_blockVersionData
          scriptVersion:     0
          slotDuration:      7000
          maxBlockSize:      2000000
          maxHeaderSize:     2000000
          maxTxSize:         4096 # 4 Kb
          maxProposalSize:   700 # 700 bytes
          mpcThd:            0.01 # 1% of stake
          heavyDelThd:       0.005 # 0.5% of stake
          updateVoteThd:     0.001 # 0.1% of total stake
          updateProposalThd: 0.1 # 10% of total stake
          updateImplicit:    10 # slots
          softforkRule:
            initThd:        0.9 # 90% of total stake
            minThd:         0.6 # 60% of total stake
            thdDecrement:   0.05 # 5% of total stake
          txFeePolicy:
            txSizeLinear:
              a: 155381 # absolute minimal fees per transaction
              b: 43.946 # additional minimal fees per byte of transaction size
          unlockStakeEpoch: 18446744073709551615 # last epoch (maxBound @Word64)
        protocolConstants: &dev_core_genesis_spec_protocolConstants
          k: 2
          protocolMagic: 55550001
          vssMinTTL: 2
          vssMaxTTL: 6
        ftsSeed: "c2tvdm9yb2RhIEdndXJkYSBib3JvZGEgcHJvdm9kYSA="
        heavyDelegation: {}
        avvmDistr: {}

    dbSerializeVersion: 0
    memPoolLimitRatio: 2 # mem pool will be limited by this value
                         # muliplied by block size limit
    # Chain quality thresholds and other constants to detect suspicious things
    nonCriticalCQBootstrap: 0.95
    criticalCQBootstrap: 0.8888
    nonCriticalCQ: 0.8
    criticalCQ: 0.654321
    criticalForkThreshold: 2 # number of blocks such that if so many blocks are
                             # rolled back, it requires immediate response
    fixedTimeCQ: 10 # Chain quality will be also calculated for this amount
                    # of seconds.
    # Mode-sensitive logging options
    webLoggingEnabled: true

  infra: &dev_infra

    # NTP
    ntpResponseTimeout: 7000000 # 7 sec
    ntpPollDelay: 300000000 # 300 sec
    ntpMaxError: 120000000 # 2 mins

    neighboursSendThreshold: 2
    kademliaDumpInterval: 4
    enhancedMessageTimeout: 360 # 6 mins
    enhancedMessageBroadcast: 2
    networkWaitLogInterval: 1 # 1s

    maxReqSize: 102 # 102 bytes
    maxInvSize: 102 # 102 bytes
    maxMempoolMsgSize: 100 # 100 bytes

  update: &dev_update
    applicationName: cardano-sl
    applicationVersion: 0
    lastKnownBlockVersion:
      bvMajor: 0
      bvMinor: 0
      bvAlt: 0
    systemTag: system

  # GodTossing
  gt: &dev_gt
    mpcSendInterval: 10 # must be less than (2 * k * slotDuration - networkDiameter)
    mdNoCommitmentsEpochThreshold: 3

  node: &dev_node
    # FIXME avieth
    # check which of these are not used and remove them.
    networkDiameter: 3
    defaultPeers: []
    mdNoBlocksSlotThreshold: 3 # should be less than 2 * k
    lightDlgConfirmationTimeout: 500
    dlgCacheParam: 500
    recoveryHeadersMessage: 20 # should be greater than k
    messageCacheTimeout: 30
    networkConnectionTimeout: 2000
    blockRetrievalQueueSize: 100
    propagationQueueSize: 100
    pendingTxResubmissionPeriod: 7 # seconds

##############################################################################
##                                                                          ##
##   Benchmarking config                                                    ##
##                                                                          ##
##############################################################################

bench: &bench
  <<: *dev

  core:
    <<: *dev_core

    genesis:
      spec:
        <<: *dev_core_genesis_spec
        initializer:
          testnetInitializer:
            testBalance:
              poors:        50000
              richmen:      4
              richmenShare: 0.99
              useHDAddresses: False
              totalBalance: 6000000000
            fakeAvvmBalance: 
              count: 100
              oneBalance: 15000000
            distribution: 
              testnetRichmenStakeDistr: []
            seed: 0
        blockVersionData:
          <<: *dev_core_genesis_spec_blockVersionData
          slotDuration:      20000
          mpcThd:            0.02 # 2% of stake
          heavyDelThd:       0.0003 # 0.03% of stake
          updateImplicit:    10000 # slots
          txFeePolicy:
            txSizeLinear:
              a: 0 # absolute minimal fees per transaction
              b: 0 # additional minimal fees per byte of transaction size
          unlockStakeEpoch: 0 # first epoch
        protocolConstants:
          <<: *dev_core_genesis_spec_protocolConstants
          k: 6
          protocolMagic: 55550007
#        heavyDelegation:
#          - pskDelegatePk: hecJCq/AX2Xn43dP7yqxK0wFQfFkNv3tM0cu/kG4xgzEvOO0coIh8epYeHdxCcoxmKIvmTJILqwJv1M+IsA4jA==
#            pskOmega:
#              getEpochIndex: 0
#            pskCert: 1d2d94b625afcfaa127974e1c6b49734cca1056c37a2228fd737e16611ca6bb78f1c254b400c5b0c9aeb3a2c9454d72eda8246aed0bd3be0cacb6f69a6475c0a
#            pskIssuerPk: LGPdjVPmSRMTG0uK33kwr/ZCgo9zTWTAa8d1hjqGjIcenTQoblqtlVFdbLOkDdKaOnDOs0XLpq1mhyNr5Mki+Q==

# Default configuration is development.

default: *dev

test:
  <<: *dev
  core:
    <<: *dev_core
    genesis:
      <<: *dev_core_genesis
      # To use a canonical JSON genesis, use the 'src' key instead of 'spec'.
      # src: './genesis.json'
      spec:
        <<: *dev_core_genesis_spec
        protocolConstants:
          <<: *dev_core_genesis_spec_protocolConstants
          k: 35
